development:
  adapter: postgresql
  database: radiant_dev
  host: localhost

test:
  adapter: postgresql
  database: radiant_test
  username: 
  password: 
  host: 

# production:  
  # adapter: sqlite3
  # database: db/production.sqlite3
  # pool: 5
  # timeout: 5000
